---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	step_start(step_start)
	get_email_details(get_email_details)
	step_end(step_end)
	__end__([<p>__end__</p>]):::last
	__start__ --> step_start;
	get_email_details --> step_end;
	step_start --> get_email_details;
	step_end --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
